// Generated from: tests\smoketest\features\exploreView_Instruments.feature
import { test } from "playwright-bdd";

test.describe('Validate instruments in Substation Explore view', () => {

  test.beforeEach('Background', async ({ Given, When, Then, page }, testInfo) => { if (testInfo.error) return;
    await Given('the user is on Detect Pro Substation Overview screen for substation under test', null, { page }); 
    await When('the user selects the "Instruments" tab', null, { page }); 
    await Then('the Instruments view should be displayed', null, { page }); 
  });
  
  test.describe('Instruments view Screen Left Navigation', () => {

    test('Example #1', { tag: ['@smoke', '@explore-view', '@instruments', '@navigation'] }, async ({ Then, And, page }) => { 
      await Then('the Instruments view left navigation menu should be visible', null, { page }); 
      await And('the Instruments view left navigation menu should contain "Home" with associated "visible, clickable"', null, { page }); 
    });

    test('Example #2', { tag: ['@smoke', '@explore-view', '@instruments', '@navigation'] }, async ({ Then, And, page }) => { 
      await Then('the Instruments view left navigation menu should be visible', null, { page }); 
      await And('the Instruments view left navigation menu should contain "Chart Filters" with associated "Disabled, not clickable"', null, { page }); 
    });

    test('Example #3', { tag: ['@smoke', '@explore-view', '@instruments', '@navigation'] }, async ({ Then, And, page }) => { 
      await Then('the Instruments view left navigation menu should be visible', null, { page }); 
      await And('the Instruments view left navigation menu should contain "App Suite" with associated "Disabled, not clickable"', null, { page }); 
    });

    test('Example #4', { tag: ['@smoke', '@explore-view', '@instruments', '@navigation'] }, async ({ Then, And, page }) => { 
      await Then('the Instruments view left navigation menu should be visible', null, { page }); 
      await And('the Instruments view left navigation menu should contain "Circuit Condition" with associated "Disabled, not clickable"', null, { page }); 
    });

    test('Example #5', { tag: ['@smoke', '@explore-view', '@instruments', '@navigation'] }, async ({ Then, And, page }) => { 
      await Then('the Instruments view left navigation menu should be visible', null, { page }); 
      await And('the Instruments view left navigation menu should contain "Substation Search" with associated "visible, clickable"', null, { page }); 
    });

    test('Example #6', { tag: ['@smoke', '@explore-view', '@instruments', '@navigation'] }, async ({ Then, And, page }) => { 
      await Then('the Instruments view left navigation menu should be visible', null, { page }); 
      await And('the Instruments view left navigation menu should contain "Settings" with associated "visible, clickable"', null, { page }); 
    });

    test('Example #7', { tag: ['@smoke', '@explore-view', '@instruments', '@navigation'] }, async ({ Then, And, page }) => { 
      await Then('the Instruments view left navigation menu should be visible', null, { page }); 
      await And('the Instruments view left navigation menu should contain "Logout" with associated "visible, clickable"', null, { page }); 
    });

  });

  test('VisNet Hub details and graphs are displayed', { tag: ['@smoke', '@explore-view', '@instruments', '@visnet-hub'] }, async ({ When, Then, And, page }) => { 
    await When('the user selects the "VisNet Hub" instrument from the Instruments list', null, { page }); 
    await Then('the "VisNet Hub" Instrument Overview should contain these fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"}]},{"cells":[{"value":"Instrument"}]},{"cells":[{"value":"Device Status"}]},{"cells":[{"value":"Last Updated"}]},{"cells":[{"value":"Last Seen"}]},{"cells":[{"value":"Serial Number"}]},{"cells":[{"value":"Instrument ID"}]},{"cells":[{"value":"Antenna Connected"}]},{"cells":[{"value":"Version"}]}]}}, { page }); 
    await And('the "VisNet Hub Details" section should contain these fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"}]},{"cells":[{"value":"MAC Address"}]},{"cells":[{"value":"SIM Serial"}]},{"cells":[{"value":"IP Address"}]},{"cells":[{"value":"Fuse Stalk Extender"}]}]}}, { page }); 
    await And('the Instruments view should display these graph components:', {"dataTable":{"rows":[{"cells":[{"value":"graph"}]},{"cells":[{"value":"Signal Strength"}]}]}}, { page }); 
  });

  test('VisNet View details and graphs are displayed', { tag: ['@smoke', '@explore-view', '@instruments', '@visnet-view'] }, async ({ When, Then, And, page }) => { 
    await When('the user selects the "VisNet View" instrument from the Instruments list', null, { page }); 
    await Then('the "VisNet View" Instrument Overview should contain these fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"}]},{"cells":[{"value":"Instrument"}]},{"cells":[{"value":"Device Status"}]},{"cells":[{"value":"Last Updated"}]},{"cells":[{"value":"Last Seen"}]},{"cells":[{"value":"Serial Number"}]},{"cells":[{"value":"Instrument ID"}]},{"cells":[{"value":"Antenna Connected"}]},{"cells":[{"value":"Version"}]}]}}, { page }); 
    await And('the "VisNet View Details" section should contain these fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"}]},{"cells":[{"value":"MAC Address"}]},{"cells":[{"value":"SIM Serial"}]},{"cells":[{"value":"IP Address"}]}]}}, { page }); 
    await And('the Instruments view should display these graph components:', {"dataTable":{"rows":[{"cells":[{"value":"graph"}]},{"cells":[{"value":"Signal Quality"}]},{"cells":[{"value":"Internal Battery Voltage"}]}]}}, { page }); 
  });

  test('Guard details and graphs are displayed', { tag: ['@smoke', '@explore-view', '@instruments', '@guard'] }, async ({ When, Then, And, page }) => { 
    await When('the user selects the "Guard" instrument from the Instruments list', null, { page }); 
    await Then('the "Guard" Instrument Overview should contain these fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"}]},{"cells":[{"value":"Instrument"}]},{"cells":[{"value":"Device Status"}]},{"cells":[{"value":"Last Updated"}]},{"cells":[{"value":"Last Seen"}]},{"cells":[{"value":"Serial Number"}]},{"cells":[{"value":"Instrument ID"}]},{"cells":[{"value":"Antenna Connected"}]},{"cells":[{"value":"Version"}]}]}}, { page }); 
    await And('the "Voltage Probe Settings" section should contain these fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"}]},{"cells":[{"value":"Voltage Probe"}]},{"cells":[{"value":"Connection Probe"}]},{"cells":[{"value":"Phase"}]}]}}, { page }); 
    await And('the "Current Probe Settings" section should contain these fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"}]},{"cells":[{"value":"Current Probe"}]},{"cells":[{"value":"Connection Probe"}]},{"cells":[{"value":"Phase"}]}]}}, { page }); 
    await And('the Instruments view should display these graph components:', {"dataTable":{"rows":[{"cells":[{"value":"graph"}]},{"cells":[{"value":"Signal Strength"}]}]}}, { page }); 
  });

  test('Reclose2 details and graphs are displayed', { tag: ['@smoke', '@explore-view', '@instruments', '@reclose2'] }, async ({ When, Then, And, page }) => { 
    await When('the user selects the "Reclose2 1.1" instrument from the Instruments list', null, { page }); 
    await Then('the "Reclose2 1.1" Instrument Overview should contain these fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"}]},{"cells":[{"value":"Instrument"}]},{"cells":[{"value":"Device Status"}]},{"cells":[{"value":"Last Updated"}]},{"cells":[{"value":"Last Seen"}]},{"cells":[{"value":"Serial Number"}]},{"cells":[{"value":"Instrument ID"}]},{"cells":[{"value":"Antenna Connected"}]}]}}, { page }); 
    await And('the "Reclose Details" section should contain these fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"}]},{"cells":[{"value":"Modbus Address"}]},{"cells":[{"value":"Uptime"}]},{"cells":[{"value":"Setup Address"}]},{"cells":[{"value":"Fuse Rating"}]},{"cells":[{"value":"Total Device Operations"}]},{"cells":[{"value":"Total Open Operations"}]},{"cells":[{"value":"Switch State"}]},{"cells":[{"value":"Switch Temperature"}]},{"cells":[{"value":"Busbar Voltage"}]},{"cells":[{"value":"Cable Voltage"}]},{"cells":[{"value":"Current RMS"}]}]}}, { page }); 
    await And('the Instruments view should display these graph components:', {"dataTable":{"rows":[{"cells":[{"value":"graph"}]},{"cells":[{"value":"Switch Temperature"}]}]}}, { page }); 
  });

});

// == technical section ==

test.beforeEach('BeforeEach Hooks', ({ $runScenarioHooks, page }) => $runScenarioHooks('before', { page }));
test.afterEach('AfterEach Hooks', ({ $runScenarioHooks }) => $runScenarioHooks('after', {  }));

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests\\smoketest\\features\\exploreView_Instruments.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":14,"pickleLine":20,"tags":["@smoke","@explore-view","@instruments","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","isBg":true,"stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view should be displayed","isBg":true,"stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view left navigation menu should be visible","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"And the Instruments view left navigation menu should contain \"Home\" with associated \"visible, clickable\"","stepMatchArguments":[{"group":{"start":57,"value":"\"Home\"","children":[{"start":58,"value":"Home","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":80,"value":"\"visible, clickable\"","children":[{"start":81,"value":"visible, clickable","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":19,"pickleLine":21,"tags":["@smoke","@explore-view","@instruments","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","isBg":true,"stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view should be displayed","isBg":true,"stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view left navigation menu should be visible","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"And the Instruments view left navigation menu should contain \"Chart Filters\" with associated \"Disabled, not clickable\"","stepMatchArguments":[{"group":{"start":57,"value":"\"Chart Filters\"","children":[{"start":58,"value":"Chart Filters","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":89,"value":"\"Disabled, not clickable\"","children":[{"start":90,"value":"Disabled, not clickable","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":24,"pickleLine":22,"tags":["@smoke","@explore-view","@instruments","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","isBg":true,"stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view should be displayed","isBg":true,"stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view left navigation menu should be visible","stepMatchArguments":[]},{"pwStepLine":26,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"And the Instruments view left navigation menu should contain \"App Suite\" with associated \"Disabled, not clickable\"","stepMatchArguments":[{"group":{"start":57,"value":"\"App Suite\"","children":[{"start":58,"value":"App Suite","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":85,"value":"\"Disabled, not clickable\"","children":[{"start":86,"value":"Disabled, not clickable","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":29,"pickleLine":23,"tags":["@smoke","@explore-view","@instruments","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","isBg":true,"stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view should be displayed","isBg":true,"stepMatchArguments":[]},{"pwStepLine":30,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view left navigation menu should be visible","stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"And the Instruments view left navigation menu should contain \"Circuit Condition\" with associated \"Disabled, not clickable\"","stepMatchArguments":[{"group":{"start":57,"value":"\"Circuit Condition\"","children":[{"start":58,"value":"Circuit Condition","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":93,"value":"\"Disabled, not clickable\"","children":[{"start":94,"value":"Disabled, not clickable","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":34,"pickleLine":24,"tags":["@smoke","@explore-view","@instruments","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","isBg":true,"stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view should be displayed","isBg":true,"stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view left navigation menu should be visible","stepMatchArguments":[]},{"pwStepLine":36,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"And the Instruments view left navigation menu should contain \"Substation Search\" with associated \"visible, clickable\"","stepMatchArguments":[{"group":{"start":57,"value":"\"Substation Search\"","children":[{"start":58,"value":"Substation Search","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":93,"value":"\"visible, clickable\"","children":[{"start":94,"value":"visible, clickable","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":39,"pickleLine":25,"tags":["@smoke","@explore-view","@instruments","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","isBg":true,"stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view should be displayed","isBg":true,"stepMatchArguments":[]},{"pwStepLine":40,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view left navigation menu should be visible","stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"And the Instruments view left navigation menu should contain \"Settings\" with associated \"visible, clickable\"","stepMatchArguments":[{"group":{"start":57,"value":"\"Settings\"","children":[{"start":58,"value":"Settings","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":84,"value":"\"visible, clickable\"","children":[{"start":85,"value":"visible, clickable","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":44,"pickleLine":26,"tags":["@smoke","@explore-view","@instruments","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","isBg":true,"stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view should be displayed","isBg":true,"stepMatchArguments":[]},{"pwStepLine":45,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view left navigation menu should be visible","stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"And the Instruments view left navigation menu should contain \"Logout\" with associated \"visible, clickable\"","stepMatchArguments":[{"group":{"start":57,"value":"\"Logout\"","children":[{"start":58,"value":"Logout","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":82,"value":"\"visible, clickable\"","children":[{"start":83,"value":"visible, clickable","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":51,"pickleLine":29,"tags":["@smoke","@explore-view","@instruments","@visnet-hub"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","isBg":true,"stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view should be displayed","isBg":true,"stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":30,"keywordType":"Action","textWithKeyword":"When the user selects the \"VisNet Hub\" instrument from the Instruments list","stepMatchArguments":[{"group":{"start":21,"value":"\"VisNet Hub\"","children":[{"start":22,"value":"VisNet Hub","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":31,"keywordType":"Outcome","textWithKeyword":"Then the \"VisNet Hub\" Instrument Overview should contain these fields:","stepMatchArguments":[{"group":{"start":4,"value":"\"VisNet Hub\"","children":[{"start":5,"value":"VisNet Hub","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":54,"gherkinStepLine":41,"keywordType":"Outcome","textWithKeyword":"And the \"VisNet Hub Details\" section should contain these fields:","stepMatchArguments":[{"group":{"start":4,"value":"\"VisNet Hub Details\"","children":[{"start":5,"value":"VisNet Hub Details","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"And the Instruments view should display these graph components:","stepMatchArguments":[]}]},
  {"pwTestLine":58,"pickleLine":52,"tags":["@smoke","@explore-view","@instruments","@visnet-view"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","isBg":true,"stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view should be displayed","isBg":true,"stepMatchArguments":[]},{"pwStepLine":59,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"When the user selects the \"VisNet View\" instrument from the Instruments list","stepMatchArguments":[{"group":{"start":21,"value":"\"VisNet View\"","children":[{"start":22,"value":"VisNet View","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":60,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then the \"VisNet View\" Instrument Overview should contain these fields:","stepMatchArguments":[{"group":{"start":4,"value":"\"VisNet View\"","children":[{"start":5,"value":"VisNet View","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":61,"gherkinStepLine":64,"keywordType":"Outcome","textWithKeyword":"And the \"VisNet View Details\" section should contain these fields:","stepMatchArguments":[{"group":{"start":4,"value":"\"VisNet View Details\"","children":[{"start":5,"value":"VisNet View Details","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":62,"gherkinStepLine":69,"keywordType":"Outcome","textWithKeyword":"And the Instruments view should display these graph components:","stepMatchArguments":[]}]},
  {"pwTestLine":65,"pickleLine":75,"tags":["@smoke","@explore-view","@instruments","@guard"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","isBg":true,"stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view should be displayed","isBg":true,"stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":76,"keywordType":"Action","textWithKeyword":"When the user selects the \"Guard\" instrument from the Instruments list","stepMatchArguments":[{"group":{"start":21,"value":"\"Guard\"","children":[{"start":22,"value":"Guard","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":77,"keywordType":"Outcome","textWithKeyword":"Then the \"Guard\" Instrument Overview should contain these fields:","stepMatchArguments":[{"group":{"start":4,"value":"\"Guard\"","children":[{"start":5,"value":"Guard","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":68,"gherkinStepLine":87,"keywordType":"Outcome","textWithKeyword":"And the \"Voltage Probe Settings\" section should contain these fields:","stepMatchArguments":[{"group":{"start":4,"value":"\"Voltage Probe Settings\"","children":[{"start":5,"value":"Voltage Probe Settings","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":69,"gherkinStepLine":92,"keywordType":"Outcome","textWithKeyword":"And the \"Current Probe Settings\" section should contain these fields:","stepMatchArguments":[{"group":{"start":4,"value":"\"Current Probe Settings\"","children":[{"start":5,"value":"Current Probe Settings","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":97,"keywordType":"Outcome","textWithKeyword":"And the Instruments view should display these graph components:","stepMatchArguments":[]}]},
  {"pwTestLine":73,"pickleLine":102,"tags":["@smoke","@explore-view","@instruments","@reclose2"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","isBg":true,"stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then the Instruments view should be displayed","isBg":true,"stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":103,"keywordType":"Action","textWithKeyword":"When the user selects the \"Reclose2 1.1\" instrument from the Instruments list","stepMatchArguments":[{"group":{"start":21,"value":"\"Reclose2 1.1\"","children":[{"start":22,"value":"Reclose2 1.1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":104,"keywordType":"Outcome","textWithKeyword":"Then the \"Reclose2 1.1\" Instrument Overview should contain these fields:","stepMatchArguments":[{"group":{"start":4,"value":"\"Reclose2 1.1\"","children":[{"start":5,"value":"Reclose2 1.1","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":76,"gherkinStepLine":113,"keywordType":"Outcome","textWithKeyword":"And the \"Reclose Details\" section should contain these fields:","stepMatchArguments":[{"group":{"start":4,"value":"\"Reclose Details\"","children":[{"start":5,"value":"Reclose Details","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":77,"gherkinStepLine":126,"keywordType":"Outcome","textWithKeyword":"And the Instruments view should display these graph components:","stepMatchArguments":[]}]},
]; // bdd-data-end