// Generated from: tests\smoketest\features\exploreView_Tabs.feature
import { test } from "playwright-bdd";

test.describe('Validate tabs in Substation Explore view', () => {

  test.beforeEach('Background', async ({ Given, page }, testInfo) => { if (testInfo.error) return;
    await Given('the user is on Detect Pro Substation Overview screen for substation under test', null, { page }); 
  });
  
  test.describe('Verify navigation to each Substation Explore view tab', () => {

    test('Example #1', { tag: ['@smoke', '@explore-view', '@navigation'] }, async ({ When, Then, And, page }) => { 
      await When('the user selects the "Substation Overview" tab', null, { page }); 
      await Then('the "Substation Overview" tab should be displayed as selected', null, { page }); 
      await And('the user should be navigated to the "Substation Overview" view', null, { page }); 
      await And('a screenshot should be captured showing the selected "Substation Overview" tab', null, { page }); 
    });

    test('Example #2', { tag: ['@smoke', '@explore-view', '@navigation'] }, async ({ When, Then, And, page }) => { 
      await When('the user selects the "Electrical" tab', null, { page }); 
      await Then('the "Electrical" tab should be displayed as selected', null, { page }); 
      await And('the user should be navigated to the "Electrical" view', null, { page }); 
      await And('a screenshot should be captured showing the selected "Electrical" tab', null, { page }); 
    });

    test('Example #3', { tag: ['@smoke', '@explore-view', '@navigation'] }, async ({ When, Then, And, page }) => { 
      await When('the user selects the "Power Quality" tab', null, { page }); 
      await Then('the "Power Quality" tab should be displayed as selected', null, { page }); 
      await And('the user should be navigated to the "Power Quality" view', null, { page }); 
      await And('a screenshot should be captured showing the selected "Power Quality" tab', null, { page }); 
    });

    test('Example #4', { tag: ['@smoke', '@explore-view', '@navigation'] }, async ({ When, Then, And, page }) => { 
      await When('the user selects the "Fault Overview" tab', null, { page }); 
      await Then('the "Fault Overview" tab should be displayed as selected', null, { page }); 
      await And('the user should be navigated to the "Fault Overview" view', null, { page }); 
      await And('a screenshot should be captured showing the selected "Fault Overview" tab', null, { page }); 
    });

    test('Example #5', { tag: ['@smoke', '@explore-view', '@navigation'] }, async ({ When, Then, And, page }) => { 
      await When('the user selects the "Events" tab', null, { page }); 
      await Then('the "Events" tab should be displayed as selected', null, { page }); 
      await And('the user should be navigated to the "Events" view', null, { page }); 
      await And('a screenshot should be captured showing the selected "Events" tab', null, { page }); 
    });

    test('Example #6', { tag: ['@smoke', '@explore-view', '@navigation'] }, async ({ When, Then, And, page }) => { 
      await When('the user selects the "Event Trending" tab', null, { page }); 
      await Then('the "Event Trending" tab should be displayed as selected', null, { page }); 
      await And('the user should be navigated to the "Event Trending" view', null, { page }); 
      await And('a screenshot should be captured showing the selected "Event Trending" tab', null, { page }); 
    });

    test('Example #7', { tag: ['@smoke', '@explore-view', '@navigation'] }, async ({ When, Then, And, page }) => { 
      await When('the user selects the "Environmental" tab', null, { page }); 
      await Then('the "Environmental" tab should be displayed as selected', null, { page }); 
      await And('the user should be navigated to the "Environmental" view', null, { page }); 
      await And('a screenshot should be captured showing the selected "Environmental" tab', null, { page }); 
    });

    test('Example #8', { tag: ['@smoke', '@explore-view', '@navigation'] }, async ({ When, Then, And, page }) => { 
      await When('the user selects the "Instruments" tab', null, { page }); 
      await Then('the "Instruments" tab should be displayed as selected', null, { page }); 
      await And('the user should be navigated to the "Instruments" view', null, { page }); 
      await And('a screenshot should be captured showing the selected "Instruments" tab', null, { page }); 
    });

    test('Example #9', { tag: ['@smoke', '@explore-view', '@navigation'] }, async ({ When, Then, And, page }) => { 
      await When('the user selects the "Load Duration" tab', null, { page }); 
      await Then('the "Load Duration" tab should be displayed as selected', null, { page }); 
      await And('the user should be navigated to the "Load Duration" view', null, { page }); 
      await And('a screenshot should be captured showing the selected "Load Duration" tab', null, { page }); 
    });

    test('Example #10', { tag: ['@smoke', '@explore-view', '@navigation'] }, async ({ When, Then, And, page }) => { 
      await When('the user selects the "Neutral Anomaly" tab', null, { page }); 
      await Then('the "Neutral Anomaly" tab should be displayed as selected', null, { page }); 
      await And('the user should be navigated to the "Neutral Anomaly" view', null, { page }); 
      await And('a screenshot should be captured showing the selected "Neutral Anomaly" tab', null, { page }); 
    });

    test('Example #11', { tag: ['@smoke', '@explore-view', '@navigation'] }, async ({ When, Then, And, page }) => { 
      await When('the user selects the "Battery Management" tab', null, { page }); 
      await Then('the "Battery Management" tab should be displayed as selected', null, { page }); 
      await And('the user should be navigated to the "Battery Management" view', null, { page }); 
      await And('a screenshot should be captured showing the selected "Battery Management" tab', null, { page }); 
    });

  });

});

// == technical section ==

test.beforeEach('BeforeEach Hooks', ({ $runScenarioHooks, page }) => $runScenarioHooks('before', { page }));
test.afterEach('AfterEach Hooks', ({ $runScenarioHooks }) => $runScenarioHooks('after', {  }));

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests\\smoketest\\features\\exploreView_Tabs.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":12,"pickleLine":19,"tags":["@smoke","@explore-view","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user selects the \"Substation Overview\" tab","stepMatchArguments":[{"group":{"start":21,"value":"\"Substation Overview\"","children":[{"start":22,"value":"Substation Overview","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the \"Substation Overview\" tab should be displayed as selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Substation Overview\"","children":[{"start":5,"value":"Substation Overview","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":15,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the user should be navigated to the \"Substation Overview\" view","stepMatchArguments":[{"group":{"start":36,"value":"\"Substation Overview\"","children":[{"start":37,"value":"Substation Overview","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":16,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And a screenshot should be captured showing the selected \"Substation Overview\" tab","stepMatchArguments":[{"group":{"start":53,"value":"\"Substation Overview\"","children":[{"start":54,"value":"Substation Overview","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":19,"pickleLine":20,"tags":["@smoke","@explore-view","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user selects the \"Electrical\" tab","stepMatchArguments":[{"group":{"start":21,"value":"\"Electrical\"","children":[{"start":22,"value":"Electrical","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the \"Electrical\" tab should be displayed as selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Electrical\"","children":[{"start":5,"value":"Electrical","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the user should be navigated to the \"Electrical\" view","stepMatchArguments":[{"group":{"start":36,"value":"\"Electrical\"","children":[{"start":37,"value":"Electrical","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":23,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And a screenshot should be captured showing the selected \"Electrical\" tab","stepMatchArguments":[{"group":{"start":53,"value":"\"Electrical\"","children":[{"start":54,"value":"Electrical","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":26,"pickleLine":21,"tags":["@smoke","@explore-view","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":27,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user selects the \"Power Quality\" tab","stepMatchArguments":[{"group":{"start":21,"value":"\"Power Quality\"","children":[{"start":22,"value":"Power Quality","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the \"Power Quality\" tab should be displayed as selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Power Quality\"","children":[{"start":5,"value":"Power Quality","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the user should be navigated to the \"Power Quality\" view","stepMatchArguments":[{"group":{"start":36,"value":"\"Power Quality\"","children":[{"start":37,"value":"Power Quality","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And a screenshot should be captured showing the selected \"Power Quality\" tab","stepMatchArguments":[{"group":{"start":53,"value":"\"Power Quality\"","children":[{"start":54,"value":"Power Quality","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":33,"pickleLine":22,"tags":["@smoke","@explore-view","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":34,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user selects the \"Fault Overview\" tab","stepMatchArguments":[{"group":{"start":21,"value":"\"Fault Overview\"","children":[{"start":22,"value":"Fault Overview","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":35,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the \"Fault Overview\" tab should be displayed as selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Fault Overview\"","children":[{"start":5,"value":"Fault Overview","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the user should be navigated to the \"Fault Overview\" view","stepMatchArguments":[{"group":{"start":36,"value":"\"Fault Overview\"","children":[{"start":37,"value":"Fault Overview","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And a screenshot should be captured showing the selected \"Fault Overview\" tab","stepMatchArguments":[{"group":{"start":53,"value":"\"Fault Overview\"","children":[{"start":54,"value":"Fault Overview","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":40,"pickleLine":23,"tags":["@smoke","@explore-view","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user selects the \"Events\" tab","stepMatchArguments":[{"group":{"start":21,"value":"\"Events\"","children":[{"start":22,"value":"Events","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":42,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the \"Events\" tab should be displayed as selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Events\"","children":[{"start":5,"value":"Events","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the user should be navigated to the \"Events\" view","stepMatchArguments":[{"group":{"start":36,"value":"\"Events\"","children":[{"start":37,"value":"Events","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And a screenshot should be captured showing the selected \"Events\" tab","stepMatchArguments":[{"group":{"start":53,"value":"\"Events\"","children":[{"start":54,"value":"Events","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":47,"pickleLine":24,"tags":["@smoke","@explore-view","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":48,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user selects the \"Event Trending\" tab","stepMatchArguments":[{"group":{"start":21,"value":"\"Event Trending\"","children":[{"start":22,"value":"Event Trending","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":49,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the \"Event Trending\" tab should be displayed as selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Event Trending\"","children":[{"start":5,"value":"Event Trending","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the user should be navigated to the \"Event Trending\" view","stepMatchArguments":[{"group":{"start":36,"value":"\"Event Trending\"","children":[{"start":37,"value":"Event Trending","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":51,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And a screenshot should be captured showing the selected \"Event Trending\" tab","stepMatchArguments":[{"group":{"start":53,"value":"\"Event Trending\"","children":[{"start":54,"value":"Event Trending","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":54,"pickleLine":25,"tags":["@smoke","@explore-view","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":55,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user selects the \"Environmental\" tab","stepMatchArguments":[{"group":{"start":21,"value":"\"Environmental\"","children":[{"start":22,"value":"Environmental","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":56,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the \"Environmental\" tab should be displayed as selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Environmental\"","children":[{"start":5,"value":"Environmental","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":57,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the user should be navigated to the \"Environmental\" view","stepMatchArguments":[{"group":{"start":36,"value":"\"Environmental\"","children":[{"start":37,"value":"Environmental","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":58,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And a screenshot should be captured showing the selected \"Environmental\" tab","stepMatchArguments":[{"group":{"start":53,"value":"\"Environmental\"","children":[{"start":54,"value":"Environmental","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":61,"pickleLine":26,"tags":["@smoke","@explore-view","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user selects the \"Instruments\" tab","stepMatchArguments":[{"group":{"start":21,"value":"\"Instruments\"","children":[{"start":22,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":63,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the \"Instruments\" tab should be displayed as selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Instruments\"","children":[{"start":5,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":64,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the user should be navigated to the \"Instruments\" view","stepMatchArguments":[{"group":{"start":36,"value":"\"Instruments\"","children":[{"start":37,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And a screenshot should be captured showing the selected \"Instruments\" tab","stepMatchArguments":[{"group":{"start":53,"value":"\"Instruments\"","children":[{"start":54,"value":"Instruments","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":68,"pickleLine":27,"tags":["@smoke","@explore-view","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user selects the \"Load Duration\" tab","stepMatchArguments":[{"group":{"start":21,"value":"\"Load Duration\"","children":[{"start":22,"value":"Load Duration","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the \"Load Duration\" tab should be displayed as selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Load Duration\"","children":[{"start":5,"value":"Load Duration","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the user should be navigated to the \"Load Duration\" view","stepMatchArguments":[{"group":{"start":36,"value":"\"Load Duration\"","children":[{"start":37,"value":"Load Duration","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":72,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And a screenshot should be captured showing the selected \"Load Duration\" tab","stepMatchArguments":[{"group":{"start":53,"value":"\"Load Duration\"","children":[{"start":54,"value":"Load Duration","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":75,"pickleLine":28,"tags":["@smoke","@explore-view","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":76,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user selects the \"Neutral Anomaly\" tab","stepMatchArguments":[{"group":{"start":21,"value":"\"Neutral Anomaly\"","children":[{"start":22,"value":"Neutral Anomaly","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":77,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the \"Neutral Anomaly\" tab should be displayed as selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Neutral Anomaly\"","children":[{"start":5,"value":"Neutral Anomaly","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the user should be navigated to the \"Neutral Anomaly\" view","stepMatchArguments":[{"group":{"start":36,"value":"\"Neutral Anomaly\"","children":[{"start":37,"value":"Neutral Anomaly","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":79,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And a screenshot should be captured showing the selected \"Neutral Anomaly\" tab","stepMatchArguments":[{"group":{"start":53,"value":"\"Neutral Anomaly\"","children":[{"start":54,"value":"Neutral Anomaly","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":82,"pickleLine":29,"tags":["@smoke","@explore-view","@navigation"],"steps":[{"pwStepLine":7,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"Given the user is on Detect Pro Substation Overview screen for substation under test","isBg":true,"stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When the user selects the \"Battery Management\" tab","stepMatchArguments":[{"group":{"start":21,"value":"\"Battery Management\"","children":[{"start":22,"value":"Battery Management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":84,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"Then the \"Battery Management\" tab should be displayed as selected","stepMatchArguments":[{"group":{"start":4,"value":"\"Battery Management\"","children":[{"start":5,"value":"Battery Management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":85,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And the user should be navigated to the \"Battery Management\" view","stepMatchArguments":[{"group":{"start":36,"value":"\"Battery Management\"","children":[{"start":37,"value":"Battery Management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":86,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And a screenshot should be captured showing the selected \"Battery Management\" tab","stepMatchArguments":[{"group":{"start":53,"value":"\"Battery Management\"","children":[{"start":54,"value":"Battery Management","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end